### ISSUE TITLE
Customize ReadMe file

### ISSUE THREAD

**Issue by aysegulsari** [8hk/AEK#1]
Customize ReadMe file with the details of the project such as:

- Project name and description

- Technology stack

- Links for the wiki pages of the project, etc.

**Comment by aysegulsari** [comment]
Since currently project details are unknown, readme file will be updated when details are announced.

**Comment by 8hk** [comment]
Project description and some information related team are inserted 92613462d5bb483ec4b12d8a08a9fe1d34cd6008
