### ISSUE TITLE
Reading Reference Papers

### ISSUE THREAD

**Issue by 8hk** [8hk/AEK#10]
There are some reference papers on the description of project given by customer. They are quite important to understand the project in depth. All of them should be read and the important key points should be taken note at wiki page. 

- [x] Ayşegül
- [x] Esma
- [x] Kerem

**Comment by 8hk** [comment]
References of project description are below

1. [Web Annotation Ref](https://www.w3.org/TR/2017/REC-annotation-model-20170223/)
1. [Entrez Help Ref](https://www.ncbi.nlm.nih.gov/books/NBK25501/)
1. [Unified Medical Language System (UMLS)](https://www.nlm.nih.gov/research/umls/index.html)

**Comment by 8hk** [comment]
To understand UMLS in depth, the [glossary ](https://www.nlm.nih.gov/research/umls/new_users/glossary.html) and [overview ](https://www.nlm.nih.gov/research/umls/new_users/online_learning/OVR_001.html)should be and reviewed first.
- Atom
- Concept
- Context
- CUI (Concept Unique Identifier)
- Content View
- Hierachy
- Metathesarus
- Semantic Network
- Semantic Type

are important keywords that should be reviewed carefully. 


Unified Medical Language System (UMLS) has strong REST API. It's [documentation ](https://documentation.uts.nlm.nih.gov/rest/search/index.html) is quite descriptive.
We can

- [Search at UMLS](https://documentation.uts.nlm.nih.gov/rest/search/index.html)
-  [Retreive UML Concept ](https://documentation.uts.nlm.nih.gov/rest/concept/index.html) (Information, Definition and Relation) 
- [Retreive UML Atoms](https://documentation.uts.nlm.nih.gov/rest/atoms/index.html) (Atoms, Parents, Ancestors and Descendant)
- [Retreive Semantic Type Information](https://documentation.uts.nlm.nih.gov/rest/semantic-network/index.html)
- [Retrieve Content View Information](https://documentation.uts.nlm.nih.gov/rest/content-views/index.html) : It has information like name, description, member count of content view.
- [Retrieve UMLS Vocubalary Metadata](https://documentation.uts.nlm.nih.gov/rest/vocabularies/index.html): Valid source abbreviations for vocabularies.

We need a licence to use REST API. Every user has api key to authenticate.
A user should post api-key to get Ticket-Granting-Ticket(TGT)
`
https://utslogin.nlm.nih.gov/cas/v1/api-key
`
TGT is valid for 8 hours. Later 8 hours ticket should be renewed with same REST call. 
The details can be found [here](https://documentation.uts.nlm.nih.gov/rest/authentication.html)
I could not make test on this API because my licence still under review by U.S. National Library of Medicine.

**Comment by heobu** [comment]
**Some useful links to understand ontologies better:**

General Information about Biomedical Ontologies and Controlled Vocabularies including UMLS: https://guides.lib.umich.edu/ontology/ontologies

Some online ontologies and tools:
Disease Ontology: https://disease-ontology.org
BioPortal: https://bioportal.bioontology.org
Ontobee: http://www.ontobee.org
Vaccine Ontology: http://www.violinet.org/vaccineontology
The Gene Ontology: http://geneontology.org

Annotations are also used in these ontologies.

**For example:**
Under "Term Information" for "aflatoxin metabolic process" [here](http://amigo.geneontology.org/amigo/term/GO:0046222), you can see a section of related links for annotations and in the annotations tab in the page.
More information can be found [here](http://wiki.geneontology.org/index.php/AmiGO_2_Manual:_Term_Page) and [here](http://wiki.geneontology.org/index.php/Annotation). Apparently some annotations were provided by users through [the GONUTS wiki](https://gowiki.tamu.edu/wiki/index.php/Main_Page).

**Comment by aysegulsari** [comment]
Unified Medical Language System (UMLS) can be described as a comprehensive list of biomedical terms for developing computer systems capable of understanding the specialized vocabulary used in biomedical information systems and health care services.

Details can be found in UMLS wiki [page](https://github.com/8hk/AEK/wiki/Unified-Medical-Language-System-(UMLS))
