### ISSUE TITLE
Remove Fractional Number of Articles

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#101]
Remove the fractional numbers for the number of articles.

![image](https://user-images.githubusercontent.com/22464721/105736603-07e91f80-5f46-11eb-8ab8-0ac201a859fe.png)

**Comment by heobu** [comment]
Also, show all the years not just a number of years.

**Comment by 8hk** [comment]
It is solved by #97
![image](https://user-images.githubusercontent.com/39605552/105747444-d70ee780-5f51-11eb-9c35-0cb36caed9d0.png)
