### ISSUE TITLE
Search Terms Might Include Extra Words in Between

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#103]
Search terms might have some words such as adjectives between the keywords within the search term.

For example: left "big" amygdala

**Comment by heobu** [comment]
Sentences could be the boundary. Or 3-4 words max could come in between.

**Comment by 8hk** [comment]
proximity and fuzzy search features of Elasticsearch are enabled.
Now user can mistype 2 char of each keyword.
and also there may be 5 words between sub search keyword at a article.

Sample 1:
![image](https://user-images.githubusercontent.com/39605552/106198608-4dffe680-61c5-11eb-9dc2-0aaca2fb4505.png)
![image](https://user-images.githubusercontent.com/39605552/106198675-63751080-61c5-11eb-979d-70ad6ba4002b.png)

Sample 2 (the order reversed)
![image](https://user-images.githubusercontent.com/39605552/106198735-7c7dc180-61c5-11eb-9c96-af6189acd81c.png)


Sample 3 (mistyping exceeds)
![image](https://user-images.githubusercontent.com/39605552/106198825-95867280-61c5-11eb-94cb-2e889a611262.png)

Sample 4 (there are more than 5 words between sub search keyword)
![image](https://user-images.githubusercontent.com/39605552/106199008-d7171d80-61c5-11eb-8db6-6dc18d2ef858.png)

**Comment by 8hk** [comment]
closing since #108 closed
