### ISSUE TITLE
Testing Entrez API

### ISSUE THREAD

**Issue by 8hk** [8hk/AEK#11]
The [Entrez](https://www.ncbi.nlm.nih.gov/search/) has very powerful API for query the medical publications. Its API should be tested in the basic level and the notes should be taken from these tests. The Entrez will be implemented into project. That's why it has very significant role on this project. The test results will be discussed during 3th Group Meeting.

- [x] Ayşegül
- [x] Esma
- [x] Kerem

**Comment by heobu** [comment]
[Quick Start](https://www.ncbi.nlm.nih.gov/books/NBK25500/)
[Sample Code](https://www.ncbi.nlm.nih.gov/books/NBK25498/)
E-Utilities: [1](https://www.ncbi.nlm.nih.gov/books/NBK25497/) [2](https://www.ncbi.nlm.nih.gov/books/NBK25499/)

**Example**

Search abstracts with the "cancer" keyword in PubMed and retrieve the IDs of 60 of them:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=cancer&retmax=60

Fetch 2 of these abstracts with the given IDs in the text format:
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=33147463,33147101&retmode=text&rettype=abstract

**Comment by 8hk** [comment]
sample postman collection for simple Entrez api call for pubmed


```
{
	"info": {
		"_postman_id": "c05d2c34-b3e6-409a-b9f4-eb5c3b9e29db",
		"name": "entrez",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "simplerequest",
			"event": [
				{
					"listen": "test",
					"script": {
						"id": "c80db599-76fd-4814-a549-73725ba35d5c",
						"exec": [
							
							"pm.environment.set(\"api_key_var\", \"\");"
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id=123456&api_key={{api_key_var}}",
					"protocol": "https",
					"host": [
						"eutils",
						"ncbi",
						"nlm",
						"nih",
						"gov"
					],
					"path": [
						"entrez",
						"eutils",
						"esummary.fcgi"
					],
					"query": [
						{
							"key": "db",
							"value": "pubmed"
						},
						{
							"key": "id",
							"value": "123456"
						},
						{
							"key": "api_key",
							"value": "{{api_key_var}}"
						}
					]
				}
			},
			"response": []
		}
	],
	"protocolProfileBehavior": {}
}
```

**Comment by 8hk** [comment]
we can use the following features of Entrez

1. Execute a search from database - ESearch (text searches),
1. Upload UID(Unique ID) to Entrez - EPost (UID uploads),
1. Download document summary or full record - ESummary (document summary downloads), 
1.  Find related data between Entrez Links - ELink (Entrez links), 
1.  Get database statics - EInfo (database statistics),
1.  Searching over global Entrez - EGQuery (global query),
1.  Getting spelling suggestions - ESpell (spelling suggestions)

We mostly will use 1,3,4,5,7. They can be found in [here ](https://www.ncbi.nlm.nih.gov/books/NBK25497/#chapter2.The_Nine_Eutilities_in_Brief) briefly. And Esma shared the Quick Start link at her comment below.



> [Quick Start](https://www.ncbi.nlm.nih.gov/books/NBK25500/)
> [Sample Code](https://www.ncbi.nlm.nih.gov/books/NBK25498/)
> E-Utilities: [1](https://www.ncbi.nlm.nih.gov/books/NBK25497/) [2](https://www.ncbi.nlm.nih.gov/books/NBK25499/)
> 
> **Example**
> 
> Search abstracts with the "cancer" keyword in PubMed and retrieve the IDs of 60 of them:
> https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=cancer&retmax=60
> 
> Fetch 2 of these abstracts with the given IDs in the text format:
> https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=33147463,33147101&retmode=text&rettype=abstract

**Comment by heobu** [comment]
In addition to the ones above mentioned **EFetch** will also be useful in retrieving abstracts.

Do we want to use the Entrez History server / Web Environment functionality and how can we make use of it.... Something to think about.

**Comment by aysegulsari** [comment]
- All E-utility requests should be made to URLs beginning with the following string:
   https://eutils.ncbi.nlm.nih.gov/entrez/eutils/
- The E-utilities without an API key will receive an error message. Example request including an API key:
   esummary.fcgi?db=pubmed&id=123456&api_key=ABCDE12345
-  Basic Searching
    esearch.fcgi?db=<database>&term=<query>
    Input: Entrez database (&db); Any Entrez text query (&term)
    Output: List of UIDs matching the Entrez query

     Example: Get the PubMed IDs (PMIDs) for articles about breast cancer published in Science in 2008
     https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi
     db=pubmed&term=science[journal]+AND+breast+cancer+AND+2008[pdat]

**Comment by aysegulsari** [comment]
Summary of the comments is added to the Entrez wiki [page](https://github.com/8hk/AEK/wiki/Entrez)
