### ISSUE TITLE
Which Articles are Annotated

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#116]
The annotator tool gives some exception about certain articles most likely due to lack of abstracts.
Check whether the tool annotates everything with an abstract or if there are other reasons some articles are not annotated.

- Limit article date to 2010 and later.
- Article dates may come from various sources. Investigate this and figure out a solution or denote that some articles indeed do not have time (with examples).

Compare the results with what is returned from PubMed.

**Comment by 8hk** [comment]
closing it since it resolved
