### ISSUE TITLE
Studying and Understanding Annotations

### ISSUE THREAD

**Issue by 8hk** [8hk/AEK#12]
[Web Annotation Data Model](https://www.w3.org/TR/annotation-model/#lifecycle-information) will play significant role during the project so the group members should study and understand the annotations. How it will be implemented into project will be discussed during 3th Group Meeting. 

- [x] Ayşegül
- [x] Esma
- [x] Kerem

**Comment by 8hk** [comment]
The main [principles of Web Annotations](https://www.w3.org/TR/annotation-model/#web-annotation-principles) should be reviewed carefully.

We will definitely use several [classes ](https://www.w3.org/TR/annotation-model/#classes)while annotating. Such as Image, Video, Text.

[Lifecycle ](https://www.w3.org/TR/annotation-model/#lifecycle-information)is also important feature of Annotations 

We may use following selectors of Web Annotation Data Model while giving annotations on the papers for specific ranges. It is quite important feature so I'm giving 3 important features of selectors. 

1.  [Text Quote Selector](https://www.w3.org/TR/annotation-model/#text-quote-selector)
1.  [Text Position Selector](https://www.w3.org/TR/annotation-model/#text-position-selector)
1.  [Refinement Selector ](https://www.w3.org/TR/annotation-model/#refinement-of-selection)

States are also important because the content of a web resource can be modified over time. However we will generally annotate from scientific papers and papers dont change over time. But the accessibility of paper may have change. So we may use [time state feature](https://www.w3.org/TR/annotation-model/#time-state) while annotating.

**Comment by heobu** [comment]
**Some useful reading**

Some papers about annotations in the context of search engines:
https://static.googleusercontent.com/media/research.google.com/tr//pubs/archive/12241.pdf
https://www.researchgate.net/publication/221542501_Semantic_Annotation_and_Search_for_Deep_Web_Services
http://infolab.stanford.edu/~theobald/pub/vldb04_compass.pdf

Annotations in Elasticsearch:
https://saskia-vola.com/named-entity-annotations-in-elasticsearch

Other:
https://www.opensemanticsearch.org/doc/datamanagement/annotation

Incorporating Wikidata and ontologies to improve search:
https://www.opensemanticsearch.org/doc/datamanagement/opendata

**Comment by aysegulsari** [comment]
Annotation can be described as defining information about a resource and making relationship between resources.

The Web Annotation Data Model provides a structured format for expressing annotations. 

The following examples may be helpful to understand (details can be found in this [link](https://www.w3.org/TR/annotation-model/#annotations)): 

1) Example Use Case: Alice has written a post that makes a comment about a particular web page. Her client creates an Annotation with the post as the body resource, and the web page as the target resource.

EXAMPLE 1: Basic Annotation Model
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno1",
  "type": "Annotation",
  "body": "http://example.org/post1",
  "target": "http://example.com/page1"
}

2) Beatrice records a long analysis of a patent, and publishes the audio on her website as an mp3. She then creates an Annotation with the mp3 as the body, and the PDF of the patent as the target.

EXAMPLE 2: External Web Resources
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno2",
  "type": "Annotation",
  "body": {
    "id": "http://example.org/analysis1.mp3",
    "format": "audio/mpeg",
    "language": "fr"
  },
  "target": {
    "id": "http://example.gov/patent1.pdf",
    "format": "application/pdf",
    "language": ["en", "ar"],
    "textDirection": "ltr",
    "processingLanguage": "en"
  }
}

3) Corina shoots a video of her comment about a website on her phone and uploads it. She associates the video with the website via an Annotation, and her client adds types as a hint to consuming systems.

EXAMPLE 3: Typing of Body and Target
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno3",
  "type": "Annotation",
  "body": {
    "id": "http://example.org/video1",
    "type": "Video"
  },
  "target": {
    "id": "http://example.org/website1",
    "type": "Text"
  }
}

**Comment by aysegulsari** [comment]
Summary of the comments is added to the Web Annotations Data Model wiki [page](https://github.com/8hk/AEK/wiki/W3C-Web-Annotation-Data-Model)
