### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#20]
Create use case diagram that shows the interaction between users and the functionality they may perform.

Recall that, each sequence diagram must include a reference identification as well as a
clear title and description. Furthermore, the users, objects and the messages you refer to
must be consistent with the use case and class diagrams. Make sure you clearly label any
arrows you use whenever applicable (i.e. hhincludesii and hhextendsii). You may refer to lower
level diagrams from higher level diagrams of the same kind.

Remember that these diagrams enable you to think through your solution as well as clearly
communicate them. This means that you should be able to read and understand the proposed
designs as well as discuss them. You may use tools that support uml Diagrams, such as
lucidchart (https://www.lucidchart.com/) service for creating uml diagrams (it offers free
accounts with your university email address), argouml (http://argouml.tigris.org/), or
umlet (http://www.umlet.com/).

- [x] Ayşegül
- [x] Esma
- [x] Kerem

**Comment by heobu** [comment]
**Search**
* Search by a query
* Search in context of dimensions consisting of key phrases consisting of key words
* Search in annotations
* Search in text

**Show summary**
* See summary info for each search combination
* See the number of articles over time (year-by-year) for each search combination

**Show detailed search results**
* See a list of search results
* Click on a search result to see the article
* Filter by publication date
* Filter by authors
* Filter by article types

**Comment by heobu** [comment]
Use cases:

- Write a main query
- Add dimension(s) (optional)
- Add keyword(s) (optional)
...
- Search
...
- Select a search result
...
- Filter by author
- Filter by publication date
- Filter by article type

**Comment by aysegulsari** [comment]
Use case diagram is added to [wiki](https://github.com/8hk/AEK/wiki/Use-Case-Diagram)
