### ISSUE TITLE
Sequence Diagrams

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#22]
Create Sequence Diagrams that specify all key use cases using the classes that you designed.

Recall that, each sequence diagram must include a reference identification as well as a
clear title and description. Furthermore, the users, objects and the messages you refer to
must be consistent with the use case and class diagrams. Make sure you clearly label any
arrows you use whenever applicable (i.e. hhincludesii and hhextendsii). You may refer to lower
level diagrams from higher level diagrams of the same kind.

Remember that these diagrams enable you to think through your solution as well as clearly
communicate them. This means that you should be able to read and understand the proposed
designs as well as discuss them. You may use tools that support uml Diagrams, such as
lucidchart (https://www.lucidchart.com/) service for creating uml diagrams (it offers free
accounts with your university email address), argouml (http://argouml.tigris.org/), or
umlet (http://www.umlet.com/).

**Comment by heobu** [comment]
- Search and see the summary results:
- [x] Ayşegül

- Pick a summary result and filter by publication date/author/article type:
- [x] Kerem

**Comment by aysegulsari** [comment]
[Search sequence diagram](https://github.com/8hk/AEK/wiki/Search-sequence-diagram)

**Comment by 8hk** [comment]
[Sequence Diagram For Filtering Results at Result Page](https://user-images.githubusercontent.com/39605552/100517889-2a0d2e00-319f-11eb-9023-232b8d017b74.png)

**Comment by 8hk** [comment]
> [Search sequence diagram](https://github.com/8hk/AEK/wiki/Search-sequence-diagram)

Hello @aysegulsari thanks for amazing work 👍 
I made some changes, please can you review them? 
[Revision 1](https://user-images.githubusercontent.com/39605552/100517926-63de3480-319f-11eb-9cd9-82dea205d57e.png)

**Comment by aysegulsari** [comment]
Thanks for the feedback Kerem! I have updated the digram [Search sequence diagram](https://github.com/8hk/AEK/wiki/Search-sequence-diagram)
