### ISSUE TITLE
Select a UI Theme/Template

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#25]
It is important to have a consistent and useful theme for the UI that can be taken advantage of. This hopefully will make the front-end implementation easier and faster.

To that end, investigate the possible UI themes that can be used for this project, make a list of the options and then decide on which one to use. Be careful about the licensing and document the findings.

**Comment by heobu** [comment]
Options:
- https://github.com/puikinsh/concept ([live](https://colorlib.com/polygon/concept/index.html))
- Some search form templates from colorlib can be found [here](https://colorlib.com/wp/free-css3-html5-search-form-examples/).
- More templates from colorlib can be found [here](https://colorlib.com) and some free ones [here](https://colorlib.com/wp/free-directory-website-templates/#html-templates).
- Some more templates [here](https://freewebsitetemplates.com).

**Comment by 8hk** [comment]
Thanks @heobu.
They are seem so great and useful for our project. 
But something came up my mind. If we will use a frontend framework, we may need to choose a UI theme suitable with chosen framework. Because some UI files are not compatible for all frameworks.
