### ISSUE TITLE
Select an Annotation Method

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#26]
It is important for the requirements of the project to have an annotation tool for the PubMed articles.

Investigate possible annotation methods and existing tools. Document what can be used and briefly describe how. Decide on a specific implementation as well.

**Comment by aysegulsari** [comment]
There is no tool directly annotate text using Web Annotation Data Model but we may use a tool like [PubTator](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3692066/), which provides a REST API, annotate articles in BioC, pubtator or JSON format. Then we may parse the content, match UMLS ontologies and produce annotations in Jsonld format.

[resource1](https://www.ncbi.nlm.nih.gov/research/pubtator/api.html)
[resource2](https://www.ncbi.nlm.nih.gov/research/pubtator/)

PubTator provides users with the opportunity to export annotated publications in batches of up to 100 in GET or 1000 in POST, in BioC, pubtator or JSON formats. To programmatically retrieve text-mined results in PubTator, one can use web queries as follows:

https://www.ncbi.nlm.nih.gov/research/pubtator-api/publications/export/[Format]?[Type]=[Identifiers]&concepts=[Bioconcepts]

Parameters' explanations:


Parameter | Description
-- | --
Format | pubtator (pubtator), biocxml (BioC-XML), biocjson (BioC-JSON) Click [here](https://www.ncbi.nlm.nih.gov/CBBresearch/Lu/Demo/tmTools/Format.html) to see the format descriptions
Type | pmids (for abstracts) or pmcids (for full-texts)
Identifiers | Single pmid (or pmcid) or list (e.g. pmids=23819905,23819906) Please note that pmcids can only be used to retrieve publications in biocxml or biocjson formats
Bioconcept | Optional comma-delimited list of the bioconcept types to include in the results, one or more of: gene, disease, chemical, species, mutation and/or cellline. If this parameter is not present, then results will contain all six bioconcepts. This parameter is only compatible with pubtator and biocxml formats. Setting concepts=none will hide all annotations.

**Comment by aysegulsari** [comment]
The list of other annotation tools APIs is in [here](http://www.pubannotation.org/docs/intro/)

**Comment by aysegulsari** [comment]
Since there is no available tool meeting our annotation requirements, we will implement our own automatic annotation script.
