### ISSUE TITLE
Select Ontologies

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#28]
It is necessary to use one or multiple ontologies for the project.

To that end, investigate existing ontologies such as UMLS, BioPortal and others suitable for the chosen subdomain, and document a list of options. Pick one or a number of them for the implementation.

There is a list of previously reviewed ontologies [here](https://github.com/8hk/AEK/issues/10#issuecomment-723426854) as well.

**Comment by heobu** [comment]
1. Disease Ontology is a repository of human diseases and has a website and API to query this repository.
Website: https://disease-ontology.org
It can list a number of synonymous phrases for the queried disease.
The query for "bipolar disorder": https://www.disease-ontology.org/api/metadata/DOID%3A3312
The repository is also available on GitHub: https://github.com/DiseaseOntology/HumanDiseaseOntology

2. Bioportal is a repository of biomedical ontologies. You can search for different classes or ontologies.
Website: https://bioportal.bioontology.org
API documentation: http://data.bioontology.org/documentation
An API key is needed for queries and can be obtained by registering quite quickly.
The query for "bipolar": http://data.bioontology.org/search?q=bipolar&apikey=API_KEY
More about Bioportal and The National Center for Biomedical Ontology: https://ncbo.bioontology.org

3. UMLS
- There is a UMLS Metathesaurus Browser which includes terms from vocabularies: https://uts.nlm.nih.gov/uts/umls/searchResults?searchString=bipolar%20disorder
This thesaurus can be reached via the above mentioned browser, or via REST API. Alternatively it can be downloaded as well. More information here: https://www.nlm.nih.gov/research/umls/knowledge_sources/metathesaurus/index.html
- There is a semantic network that includes a number of categories (semantic types) and relationships between them. Similarly this can also used with via its browser or REST API.
A ticket is needed to use the REST API here.
https://uts-ws.nlm.nih.gov/rest/search/current?string=bipolar disorder&ticket=TICKET

4. Ontobee is a linked data server for ontologies.
One of the ontologies contained within is the Mental Disease Ontology.
http://www.ontobee.org/ontology/MFOMD

**Comment by 8hk** [comment]
I think the UMLS and BioPortal are very useful as ontology. It would be easy to implement them into our project.

**Comment by heobu** [comment]
I liked the UMLS metathesaurus and that one might be better suited for our work than the UMLS semantic network.
I also liked the Bioportal and that one also searches in multiple ontologies for the concept you are looking for.
