### ISSUE TITLE
Select a Backend Framework

### ISSUE THREAD

**Issue by 8hk** [8hk/AEK#29]
Using a backend framework would reduce the work load and make our code more simple&clean. There are multiple frameworks from Java to Python.
We need to select one of them for our project.

**Comment by heobu** [comment]
Options (add below):
- [ ] Django

**Comment by 8hk** [comment]
Elasticsearch has official Python client. So we can easily implement it with using Django!
We also have some background about Django from previous term. Django seems great for me 👍

**Comment by aysegulsari** [comment]
Apart from the points that Kerem indicates about Django, since all of us have experience on developing with Django from SWE 573 class, I think it is the best option for us 👍!

**Comment by aysegulsari** [comment]
Since everybody is ok with Django, Django it is 👍
