### ISSUE TITLE
Update Use Case Diagram 

### ISSUE THREAD

**Issue by 8hk** [8hk/AEK#33]
Use case diagram is added to [wiki](https://github.com/8hk/AEK/wiki/Use-Case-Diagram)

_Originally posted by @aysegulsari in https://github.com/8hk/AEK/issues/20#issuecomment-735223096_

The current version seems ok but our customer requires some improvements for use case diagram such as

- [x] Include and extend features should be added into current diagram. For example add keyword, dimension -> search (include) or search -> filtering (include)
- [x] Adding "View Detailed Search" or User
- [x] Adding system as actor to describe annotation. For example relation between AnnotatorTool and Ontology. 
- [x] Adding Entrez as actor

**Comment by aysegulsari** [comment]
@8hk I have updated the use case diagram according to your comments but could not understand the second one. Would you please help me to understand it right? After selecting an option from the summary page we will see a page including the list of articles and filtering options. Apart form filtering options are we going to have a feature related to detailed seach in here or you mean somewhere else?

![image_2020-12-06_171526](https://user-images.githubusercontent.com/2751698/101282500-a2e73800-37e6-11eb-960b-4e4db9fdd843.png)

**Comment by 8hk** [comment]
@aysegulsari sorry for my mistake. I wrote incorrect sentence. It should be "Adding "View Detailed Search" for User"
User can look the options from summary page and analyze the difference between options from summary page. I think this is missing part of Use Case Diagram. Hope it helps ✌️

**Comment by aysegulsari** [comment]
Thank @8hk 👍 
The final version of the diagram is in [here](https://github.com/8hk/AEK/wiki/Use-Case-Diagram)
