### ISSUE TITLE
Update Sequence Diagrams

### ISSUE THREAD

**Issue by 8hk** [8hk/AEK#34]
> [Search sequence diagram](https://github.com/8hk/AEK/wiki/Search-sequence-diagram)

Hello @aysegulsari thanks for amazing work 👍 
I made some changes, please can you review them? 
[Revision 1](https://user-images.githubusercontent.com/39605552/100517926-63de3480-319f-11eb-9cd9-82dea205d57e.png)

_Originally posted by @8hk in https://github.com/8hk/AEK/issues/22#issuecomment-735237754_

[Sequence Diagram For Filtering Results at Result Page](https://user-images.githubusercontent.com/39605552/100517889-2a0d2e00-319f-11eb-9023-232b8d017b74.png)

_Originally posted by @8hk in https://github.com/8hk/AEK/issues/22#issuecomment-735237616_

The current versions of diagrams seems good but our customer requires some improvements such as

1. - [ ]  Adding Annotation  as Activity Diagram (optional)
1. - [x]  Remove the functions like RefreshSearchPage() and loop at Search Sequence Diagram
1. - [x]  Make more visible the main query at Search Sequence Diagram to make project more understandable
1. - [x] Change the SearchResultText as List of Annotations
1. - [x]  Change the name functions like SearchResultText(Search Sequence) SearchResult(Filtering) [such as List of Article]
1. - [ ]   Article or Document class may be inserted into Search Sequence Diagram
1. - [x]  Arrange the arrows that coming after the DatabaseContext. 
1. - [x]  Reduce Article List could be added into Filtering Sequence (optional)

**Comment by 8hk** [comment]
updated 2, 4, 5, 7, and 8. problems. But we may need the review places in red circle at Search Sequence
![image](https://user-images.githubusercontent.com/39605552/101244707-0d31a700-3719-11eb-9cca-a959a2f58ff5.png)

**Comment by aysegulsari** [comment]
[Search sequence diagram](https://github.com/8hk/AEK/wiki/Search-sequence-diagram) is updated.
