### ISSUE TITLE
Annotator

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#37]
Articles need to be annotated.

Develop an annotator tool using Python.
This tool stores annotations in a MongoDB conforming to jsonld and W3C standards.

- Retrieve all articles in the bipolar disorder subdomain.
- Retrieve all entries in the ontology.
- Go over each entry in the ontology and search for it an article.
- Create annotation entries in the database.
- Do this for all articles.

Each annotation entry in the database should include these details: **(which part in the text?)**, ontology entry, article link (URL), creation date, the article it corresponds to in our system.
body: the entry from ontology - this can include multiple entries if more than one ontology is used, or there are multiple "same as" terms from the same ontology.
target: the article **(+which part in the article if necessary)**

In addition to annotations, in a separate table/database, the following information should be kept for each article: abstract, authors, publication date, article type and link.

**Comment by heobu** [comment]
For now, we are only annotating the whole article, and not certain parts of it.

- [x] [Task 1](https://github.com/8hk/AEK/issues/41): Retrieve all entries (classes) in the ontology: http://data.bioontology.org/ontologies/ONTOLOGY_ACRONYM/classes?apikey=API_KEY

- [ ] [Task 2](https://github.com/8hk/AEK/issues/42): Go over each entry in the ontology and search for it in an article. Create annotation entries in the database. (target: article, not certain phrases in the article _- for now_)

**Comment by heobu** [comment]
It appears we should annotate by not targeting the whole article, but certain phrases in each one.
For now we may annotate the whole article in [this](https://github.com/8hk/AEK/issues/42) issue, but in future we plan to amend that with [this](https://github.com/8hk/AEK/issues/46) one.

**Comment by aysegulsari** [comment]
Since database insertion part could not be finished the milestone to of the issue is postponed.
