### ISSUE TITLE
Create Personal Wiki Pages

### ISSUE THREAD

**Issue by 8hk** [8hk/AEK#5]
Each group member need to create a personal wiki page.
Personal page can show your background, programming skills, contact details etc.

- [x] Ayşegül
- [x] Esma
- [x] Kerem

**Comment by 8hk** [comment]
[Here](https://github.com/8hk/AEK/wiki/Hasan-Kerem-Ocakoğlu) is my personal wiki page 😃

**Comment by aysegulsari** [comment]
[Here](https://github.com/8hk/AEK/wiki/Aysegul-Sari-Karabiyik) is mine
