### ISSUE TITLE
NLTK for Tokenization

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#62]
There are two points that might require some tokenization of text:
- Search query keywords in annotations/article
- Search annotation keywords in article

To that end it might be a good idea to pre-process the text. NLTK offers some tools for this purpose.

Investigate and document where and how we can use it.
Add some quick improvements to the current codebase if possible. Some more might be implemented later on.

**Comment by 8hk** [comment]
research is done, simple usage of NLTK is documented at [wiki page](https://github.com/8hk/AEK/wiki/NLTK-Operations).

NLTK does not provide the indexes of multiple keyword withing the given sentence. We need to write own code. Also I found two different approaches and included them into wiki page also.

We also need to be careful while using the NLTK features. Some of them removing the words from sentence and finding index of a keyword at returning sentence would not be same as with original sentence!
