### ISSUE TITLE
Summary Page Top Fields

### ISSUE THREAD

**Issue by heobu** [8hk/AEK#76]
Store publication date,top keywords and authors for each article in annotated_article_ids.

**Comment by 8hk** [comment]
I also included
- abstract
- institution list
- author list
- journal name
- journal link

![image](https://user-images.githubusercontent.com/39605552/103287305-41844480-49f3-11eb-88a7-d370e0be8ea5.png)


When a article stored into annotated_article_ids column, it will not be stored again. I prevented the duplicate entries.
