### ISSUE TITLE
Search results update for article-annotation pairs

### ISSUE THREAD

**Issue by aysegulsari** [8hk/AEK#86]
Currently for each annotation on search result is created. 

For example:
73 is not the article count, it is the annotation count
![image](https://user-images.githubusercontent.com/2751698/104651504-ce542100-56c8-11eb-8f5a-5d0eeced81ce.png)

For this article (33420255) since there are 9 annotations article counted more than once:
![image](https://user-images.githubusercontent.com/2751698/104651715-15daad00-56c9-11eb-9c40-4f7a0a209c7f.png)

I think we need to update it in the backend. What do you think about this?

**Comment by 8hk** [comment]
yes you are absolutely, right, since we are storing the id as article/id format the logic should be updated. That's why the duplicate papers coming from backend

**Comment by 8hk** [comment]
![image](https://user-images.githubusercontent.com/39605552/104712383-87e7dc00-5733-11eb-9227-045c3e94573b.png)
closing issue since we solved with  #89
